# Generated by Django 6.0.3 on 2026-04-16 16:30

from django.db import migrations

def add_default_categories(apps, schema_editor):
    Category = apps.get_model('reports', 'Category')
    categories = ['Voirie', 'Éclairage public', 'Déchets', 'Eau', 'Électricité', 'Autre']
    
    for cat_name in categories:
        Category.objects.get_or_create(name=cat_name)

class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0001_initial'),  # Assure-toi que c'est bien le nom de ta migration initiale
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]